// Operator-side prover + Foundry fixture generator (N=4 test instance).
// Scenario: one balanced peak session (r = c = rho = 15.16), netputs
// [100, 50, -80, -70] kW -> exact amounts, dayNet = 0.
// Emits TWO proofs over the SAME old balances:
//   - honest:   amounts = netput * rho
//   - dishonest: 200 units moved from slot 0 to slot 1 (sum unchanged)
// Usage: node prove_day.js

const { buildPoseidon } = require("circomlibjs");
const snarkjs = require("snarkjs");
const fs = require("fs");

const N = 2;
const SHIFT = 1n << 127n;
const WAD = 10n ** 18n;
const RHO = 1516n * WAD / 100n; // 15.16e18

const NETPUTS = [100n * WAD, -100n * WAD];
const rand = () => BigInt("0x" + require("crypto").randomBytes(31).toString("hex"));

async function prove(P2, oldBals, olds, amounts, deltas) {
    const input = { oldC: [], amtC: [], newC: [], delta: [], oldBal: [], oldR: [], amt: [], amtR: [], newR: [] };
    const open = [];
    for (let n = 0; n < N; n++) {
        const amtR = rand(), newR = rand();
        const amtS = amounts[n] + SHIFT;
        const newBal = oldBals[n] + amounts[n] + deltas[n];
        if (newBal < 0n) throw new Error(`insolvent slot ${n}`);
        input.oldBal.push(oldBals[n].toString());
        input.oldR.push(olds[n].r.toString());
        input.amt.push(amtS.toString());
        input.amtR.push(amtR.toString());
        input.newR.push(newR.toString());
        input.oldC.push(olds[n].C.toString());
        input.amtC.push(P2(amtS, amtR).toString());
        input.newC.push(P2(newBal, newR).toString());
        input.delta.push((deltas[n] + SHIFT).toString());
        open.push({ amtShifted: amtS.toString(), amtR: amtR.toString(), newBal: newBal.toString(), newR: newR.toString() });
    }
    const { proof, publicSignals } = await snarkjs.groth16.fullProve(
        input, "build/daybatch_js/daybatch.wasm", "db_final.zkey");
    const calldata = await snarkjs.groth16.exportSolidityCallData(proof, publicSignals);
    const [a, b, c, pubs] = JSON.parse("[" + calldata + "]");
    return { a, b, c, pubs, open, publicSignals };
}

function solBlock(tag, fx) {
    let s = "";
    s += `    function ${tag}A() internal pure returns (uint256[2] memory p) { p = [uint256(${fx.a[0]}), uint256(${fx.a[1]})]; }\n`;
    s += `    function ${tag}B() internal pure returns (uint256[2][2] memory p) { p = [[uint256(${fx.b[0][0]}), uint256(${fx.b[0][1]})], [uint256(${fx.b[1][0]}), uint256(${fx.b[1][1]})]]; }\n`;
    s += `    function ${tag}C() internal pure returns (uint256[2] memory p) { p = [uint256(${fx.c[0]}), uint256(${fx.c[1]})]; }\n`;
    // pubs order: [sumShifted, oldC[4], amtC[4], newC[4], delta[4]]
    s += `    function ${tag}Sum() internal pure returns (uint256) { return ${fx.pubs[0]}; }\n`;
    s += `    function ${tag}AmtC() internal pure returns (uint256[2] memory p) { p = [uint256(${fx.pubs[3]}), uint256(${fx.pubs[4]})]; }\n`;
    s += `    function ${tag}NewC() internal pure returns (uint256[2] memory p) { p = [uint256(${fx.pubs[5]}), uint256(${fx.pubs[6]})]; }\n`;
    s += `    function ${tag}Open0() internal pure returns (uint256 amtShifted, uint256 amtR) { return (${fx.open[0].amtShifted}, ${fx.open[0].amtR}); }\n`;
    return s;
}

async function main() {
    const poseidon = await buildPoseidon();
    const F = poseidon.F;
    const P2 = (x, y) => F.toObject(poseidon([x, y]));

    const oldBals = [5000n * WAD, 5000n * WAD];
    const olds = oldBals.map(b => { const r = rand(); return { r, C: P2(b, r) }; });
    const deltas = [0n, 0n];

    const honest = NETPUTS.map(n => n * RHO / WAD);        // exact, sums to 0
    const bad = [...honest];
    bad[0] -= 200n * WAD; bad[1] += 200n * WAD;            // redistribution, sum unchanged

    const H = await prove(P2, oldBals, olds, honest, deltas);
    const D = await prove(P2, oldBals, olds, bad, deltas);

    let sol = `// SPDX-License-Identifier: MIT\n// AUTO-GENERATED by zk/prove_day.js — do not edit\npragma solidity >=0.8.19;\n\nlibrary ZKFixture {\n`;
    sol += `    function oldC() internal pure returns (uint256[2] memory p) { p = [uint256(${olds[0].C}), uint256(${olds[1].C})]; }\n`;
    sol += solBlock("honest", H);
    sol += solBlock("bad", D);
    sol += `}\n`;
    fs.writeFileSync("ZKFixture.sol", sol);
    fs.writeFileSync("openings.json", JSON.stringify({ honest: H.open, bad: D.open }, null, 1));
    console.log("fixtures written; honest sum:", H.publicSignals[0], "bad sum:", D.publicSignals[0]);
    process.exit(0);
}
main().catch(e => { console.error(e); process.exit(1); });
