[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@prb/math/=lib/prb-math/",
    "@openzeppelin/=lib/openzeppelin-contracts/"
]
code_size_limit = 100000
via_ir = true
optimizer = true
