// SPDX-License-Identifier: MIT
// AUTO-GENERATED by zk/prove_day.js — do not edit
pragma solidity >=0.8.19;

library ZKFixture {
    function oldC() internal pure returns (uint256[2] memory p) { p = [uint256(10258459069921802905906260783392566390312324808398239804412121924359393045787), uint256(10795682024258703092249806336402374985846676832698452520305250075143547921604)]; }
    function honestA() internal pure returns (uint256[2] memory p) { p = [uint256(0x13bcb9ba247f9f02643bbe4fbd5b0c7a48ec702d7affa18ce54794d9cafd6dcf), uint256(0x21b8853dc56f7bd2d1f0d785f887f2d526b46c7a94734d59867843bf2a75d708)]; }
    function honestB() internal pure returns (uint256[2][2] memory p) { p = [[uint256(0x27f38969ebdeb4e1b43f1319aa765f1ecc06d6e9439cf79224b0eb78e23b6843), uint256(0x2655d6a0e12bd8dbbdcfb24f441597ae926127f2920a4c1bd515c76fc7242450)], [uint256(0x2a70641d0171e3373db813b3107107c3636af7dcf1e9cc8c718d2a008c9f92a2), uint256(0x257d5d9c8670b6eeed6a198f0b837a7e8569d7b9b265c54c2a1b9b97f6c43158)]]; }
    function honestC() internal pure returns (uint256[2] memory p) { p = [uint256(0x26203c1b9e258eacecde1514a5cc752ebee6727a7f4e76b2afb36e3d9cac455b), uint256(0x0e76d678eb108cf004af0cde56db307a5a9296397800b5fdbd6071e29bfa721e)]; }
    function honestSum() internal pure returns (uint256) { return 0x0000000000000000000000000000000100000000000000000000000000000000; }
    function honestAmtC() internal pure returns (uint256[2] memory p) { p = [uint256(0x006d7761a630af36fe638600406729a5118d2fb023fc6a76fd8426a7c2a6c69b), uint256(0x1b60f13075fa0880e7ed1feb00851c770ac0e1294256ad8e75616c890a0b4455)]; }
    function honestNewC() internal pure returns (uint256[2] memory p) { p = [uint256(0x20b70f9b2bc5e158ca7056b355c3305599e2d31fe2688c744cf20bf38f5fc3c8), uint256(0x1301fbd709f9166c3e5b48b88a0d69f94c72063012422c548f79eef7a3b1c95b)]; }
    function honestOpen0() internal pure returns (uint256 amtShifted, uint256 amtR) { return (170141183460469233247687303715884105728, 202045156173490947025335333937414564039455536418645780338590364262535082664); }
    function badA() internal pure returns (uint256[2] memory p) { p = [uint256(0x1024243512ef626ded1fcc43f459a5a6e42b479736bbd99e5d830eb54a205ad5), uint256(0x0dbeabe0c4f552419edc8507cede5b5d586b98ee725a147131378699948be9b2)]; }
    function badB() internal pure returns (uint256[2][2] memory p) { p = [[uint256(0x1e4b6bfde70b6fc2ae4ae697658777c0bdccbf2d15a4330d5559c6331af3d86f), uint256(0x180eee80ad1226d67fcd5ffb1e4a4b56118fab0936ccf2fd29aa34f9fdf24e5f)], [uint256(0x00cce2b1791c4f09f5d74b2180ea77ee8509d7dcb042e745df1096241d8554a2), uint256(0x1d56a26e17a171d333bdabbe730ff61172bc14ecb75aa02e830dbb6814427717)]]; }
    function badC() internal pure returns (uint256[2] memory p) { p = [uint256(0x273a8f5edf39d7ca3b1b7612177e2abc61b59501a4cd30bd1ae3765adc68385a), uint256(0x100f9ba6319f03502fd59d4d72b1ec50aae79c718b8b2fdaed5f16150f6c5365)]; }
    function badSum() internal pure returns (uint256) { return 0x0000000000000000000000000000000100000000000000000000000000000000; }
    function badAmtC() internal pure returns (uint256[2] memory p) { p = [uint256(0x0009592e3a43bfdbf1c2b15ee5a9ec66c4690a8417ca04466472daa2f9b04564), uint256(0x1a97502c61faef8eb7a110c7d8fae7fd741e22b7076f9b18acabb0a64a8d268c)]; }
    function badNewC() internal pure returns (uint256[2] memory p) { p = [uint256(0x073afd924881111b4807e2e91c393983fa4015636e92c2cbdb6ae066fe8c76e7), uint256(0x14e55b7e9e0f1973978cfd92507e5372da01027fa24e4247898702c2ce0efc5d)]; }
    function badOpen0() internal pure returns (uint256 amtShifted, uint256 amtR) { return (170141183460469233047687303715884105728, 79217368944107816958809149927319236643128549880428966707363252886822855576); }
}
